server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/speakify
    username: root
    password: 251204

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com         # địa chỉ máy chủ SMTP của bạn
    port: 587                       # cổng SMTP, thường là 587 cho TLS hoặc 465 cho SSL
    username: hellospeakify@gmail.com
    password: toec rqmi xpzc pvou
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

jwt:
  signerKey: "qUIO01I4tQtECy3nFMP4kI1RK27VqetVfCMf+SQJpnL+xVN9Cv1w7HCkvEPsGTVW"
  token-valid-duration: 86400  #seconds
  token-refreshable-duration: 864000  #seconds 10 days

app-init:
  admin-password: admin
  admin-name: admin
  admin-email: admin@gmail.com